name: Automatically publish to Modrinth and CurseForge
# This action is triggered when a release is created/published
# The release title is used as version name
# The release tag is used as the version number
# The release description is used as the changelog
on:
  workflow_dispatch:
  release:
    types: [ published ]

env:
  JAVA_VERSION: 17
  MOD_LOADERS: forge
  GAME_VERSIONS: |
    1.20.1
    1.20.2
    1.20.4
    1.20.6
  GAME_VERSION_FILTER: releases
  VERSION_TYPE: beta
  PRIMARY_FILE_GLOB: StargateEarlyLoading-*-forge.jar

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-actions
    permissions:
      contents: write
    outputs:
      tag_version: ${{ env.TAG }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'
      - name: Setup Gradle Wrapper
        run: chmod +x gradlew
      - name: Extract and process tag version
        id: extract_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [[ "$TAG" == v* ]]; then
            TAG=${TAG:1}
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Set version in gradle.properties
        run: |
          sed -i "s/^mod_version=.*/mod_version=${{ env.TAG }}/" gradle.properties
      - name: Run tests
        run: ./gradlew test
      - name: Build Release
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/${{ env.PRIMARY_FILE_GLOB }}

  publish-to-github:
    needs: build
    runs-on: ubuntu-latest
    environment: github-actions
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts
      - name: Publish to GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-prerelease: false
          files: artifacts/${{ env.PRIMARY_FILE_GLOB }}
          version-type: ${{ env.VERSION_TYPE }}
          loaders: ${{ env.MOD_LOADERS }}
          game-versions: ${{ env.GAME_VERSIONS }}
          game-version-filter: ${{ env.GAME_VERSION_FILTER }}
          java: ${{ env.JAVA_VERSION }}
  
  publish-to-curseforge:
    needs: build
    runs-on: ubuntu-latest
    environment: github-actions
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts
      - name: Publish to Curseforge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1205356
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: artifacts/${{ env.PRIMARY_FILE_GLOB }}
          version-type: ${{ env.VERSION_TYPE }}
          loaders: ${{ env.MOD_LOADERS }}
          game-versions: ${{ env.GAME_VERSIONS }}
          game-version-filter: ${{ env.GAME_VERSION_FILTER }}
          java: ${{ env.JAVA_VERSION }}

  publish-to-modrinth:
    needs: build
    runs-on: ubuntu-latest
    environment: github-actions
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: OMhADUE0
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: artifacts/${{ env.PRIMARY_FILE_GLOB }}
          version-type: ${{ env.VERSION_TYPE }}
          loaders: ${{ env.MOD_LOADERS }}
          game-versions: ${{ env.GAME_VERSIONS }}
          game-version-filter: ${{ env.GAME_VERSION_FILTER }}
          java: ${{ env.JAVA_VERSION }}
