name: Automatically publish to Modrinth and CurseForge
# This action is triggered when a release is created/published
# The release title is used as version name
# The release tag is used as the version number
# The release description is used as the changelog
on:
  release:
    types: [published]
jobs:
  publish-to-curseforge:
    runs-on: ubuntu-latest
    environment: github-actions
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
          
      - name: Setup Gradle Caches
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup Gradle Wrapper
        run: chmod +x gradlew

      - name: Build Release
        run: ./gradlew build
        
      - name: Publish to Curseforge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # The unique identifier of your CurseForge project.
          curseforge-id: 1205356
          # Your CurseForge API token.
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          # Your GitHub API token.
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-prerelease: true
          # A glob determining the primary files to upload.
          files-primary: build/libs/stargate_early_loading-*.jar
          # The version type - alpha, beta, or release.
          version-type: alpha
          # An array of supported mod loaders.
          loaders: neoforge
          # An array of supported Minecraft versions.
          game-versions: |
            [1.21,1.21.4]
          game-version-filter: none
        # An array of Java versions compatible with your project.
        java: 
        - 21
